# Generated by Django 2.0 on 2019-06-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(default=0)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('signatureUrl_one', models.URLField()),
                ('signatureUrl_two', models.URLField()),
            ],
            options={
                'db_table': 'contract',
            },
        ),
    ]
